using System;

namespace AICore.Services.Types.Response
{
    /// <summary>
    /// Represents the response from the AI Embedding model.
    /// The response includes an array of data objects containing embeddings and corresponding indices, and also the model used for generating embeddings.
    /// </summary>
    [Serializable]
    public class AIEmbeddingResponse
    {
        /// <summary>
        /// An array of AIEmbeddingResponseData objects. Each object holds the actual embedding vectors and their corresponding indices.
        /// </summary>
        public AIEmbeddingResponseData[] data;
        
        /// <summary>
        /// The AI model used for generating embeddings.
        /// </summary>
        public string model;
    }

    /// <summary>
    /// Contains the details of each embedding generated by the AI embedding service. 
    /// This includes the actual embedding vector and its corresponding index.
    /// </summary>
    [Serializable]
    public class AIEmbeddingResponseData
    {
        /// <summary>
        /// The embedding vector as an array of floating-point values.
        /// </summary>
        public float[] embedding;
        
        /// <summary>
        /// The index corresponding to the embedding. This is useful for mapping embeddings back to original data points.
        /// </summary>
        public int index;
    }
}