namespace FrameworkCore.MVC
{
    public enum GameControllerEvents
    {
        Start,
        Update,
        LateUpdate,
        FixedUpdate,
        OnDestroy,
        OnEnable,
        OnDisable,
        OnCollisionEnter,
        OnCollisionExit,
        OnCollisionStay,
        OnTriggerEnter,
        OnTriggerExit,
        OnTriggerStay,
        OnMouseDown,
        OnMouseEnter,
        OnMouseExit,
        OnCollisionEnter2D,
        OnCollisionExit2D,
        OnCollisionStay2D,
        OnTriggerEnter2D,
        OnTriggerExit2D,
        OnTriggerStay2D,
        OnDrag,
        OnBeginDrag,
        OnEndDrag,
        OnBecameInvisible,
    }
}