namespace AIAgent.Types.Data
{
    /// <summary>
    /// This class represents the response generated by an AI agent.
    /// </summary>
    public class  AgentResponse
    {
        /// <summary>
        /// Represents the content of the response message that is generated by the AI agent.
        /// </summary>
        public string message;

        /// <summary>
        /// Represents the emotional state of the AI agent at the time of generating the response.
        /// </summary>
        public string emotion;
    }
}